# Generated by Django 5.2.1 on 2025-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('meetup', 'Meetup'), ('conference', 'Conference'), ('webinar', 'Webinar')], max_length=50)),
            ],
        ),
    ]
