# Generated by Django 5.2.1 on 2025-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('type', models.CharField(choices=[('CONF', 'Conferência'), ('MEET', 'Encontro'), ('webinar', 'Webinar')], max_length=50, verbose_name='Tipo')),
                ('categories', models.ManyToManyField(blank=True, to='guests.category')),
                ('guest_groups', models.ManyToManyField(blank=True, to='guests.guestgroup')),
            ],
        ),
    ]
