# Generated by Django 5.2.1 on 2025-06-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_categories_remove_event_guest_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria (Evento)', 'verbose_name_plural': 'Categorias (Evento)'},
        ),
        migrations.AlterModelOptions(
            name='guestgroup',
            options={'verbose_name': 'Grupo de Convidados (Evento)', 'verbose_name_plural': 'Grupos de Convidados (Evento)'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='category',
            field=models.ForeignKey(limit_choices_to={'event_id': models.F('event_id')}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='events.category'),
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='guestgroup',
            unique_together={('event', 'name')},
        ),
    ]
