# Generated by Django 5.2.1 on 2025-06-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestgroup',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GuestGroup',
        ),
    ]
